# Generated by Django 4.1.7 on 2023-03-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload',
            field=models.FileField(null=True, upload_to='blog/uploads/'),
        ),
    ]
