# Generated by Django 4.1.7 on 2023-03-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='introduce',
            new_name='content',
        ),
    ]
